# Generated by Django 5.0.4 on 2024-04-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0002_brand_alter_car_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="cars/"),
        ),
        migrations.AddField(
            model_name="car",
            name="plate",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
